### PR TITLE
:lipstick: Add links to author profiles

### PR DESCRIPTION
**Pull request by ganm0r**

### CODE REVIEW

**Comment by ganm0r** [comment]
Good evening :sparkles: . Any reason to not add on-hover effect for project repository redirect?

**Comment by grewscant** [comment]
If we have more contributors in the future, adding links for all of them can get expensive.

**Comment by grewscant** [comment]
I'm adding a "Contributors" section to the README, all links to profiles will be added there :wink:

**Comment by grewscant** [comment]
@all-contributors please add @ganm0r for multiple PRs

**Comment by grewscant** [comment]
@all-contributors please add @ganm0r for code

**Pull request closed without merging**
